### PR TITLE
Removed shooting positions & trees on rifle range

### PR DESCRIPTION
**Pull request by JoramD**
Removed shooting positions objects from cqb/shoothouse area via hide terrain objects module

**When merged this pull request will:**
- Remove shooting position from the killhouse area by using 2 hide terrain objects modules.

### CODE REVIEW

**Comment by jonpas** [comment]
"Shooting positions objects"? What are those?

Can we also remove trees/bushes from Basic Rifle range?

**Comment by JoramD** [comment]
Those are the pads you sit/lay on at the shooting ranges. 
I will remove those bushes, didn't know if it was intended or not :)

**Comment by SyMP2005** [comment]
Nice!
No it was not intended to have bushes/trees there, but at the time there was no decent way of doing it iirc.

**Comment by SyMP2005** [comment]
I just checked out the branch @JoramD0.

Were the trees suppose to be gone on the rifle range? Because I still see them there.
Or is this a multiplayer thing that can only be seen on the server?

**Comment by JoramD** [comment]
Oh yea, forgot to mention. I only removed the trees in the middle of the range since, if you want I can remove the rest aswell. It just looked a little empty without any trees at all

**Comment by SyMP2005** [comment]
Ah ok, get rid of them all if you can :)

**Comment by jonpas** [comment]
@SyMP2005, they don't block anything, the ones potentially blocking are removed, just fyi.

**Comment by JoramD** [comment]
Eh, okay, what am I doing? xD

So I can think of a few possibilities:
* Have no bushes or rocks
* Only have rocks
* Only remove bushes in the center of the shooting range (like before)
I can commit any of these whenever :)

**Comment by jonpas** [comment]
Ultimately up to Rory, this is his project. :)

**Comment by JoramD** [comment]
Then I will commit option 2 tomorrow morning :)

**Comment by SyMP2005** [comment]
Yeah I always wanted the trees gone on the range, doesn't make much sense to have trees there IMO.

Thanks!

**Pull request merged**
