### PR TITLE
Textures now use 3den texture attributes

### LINKED ISSUE #67: Use Eden texture attribute for custom object textures
Instead of `this setObjectTexture [0, "texture.paa"];` in the init field use the new Eden object attribute for textures, added in Arma 3 v1.64.

### PR DESCRIPTION
**Pull request by JoramD**
Whiteboards, laptops and tablets now use eden texture attributes

**When merged this pull request will:**
- Have laptops, tablets and whiteboards use the 3den texture attribute instead of setObjectTexture.

Close #67

### CODE REVIEW

**Comment by jonpas** [comment]
This is bugged unless you PBO the mission, it should be tested with a dedicated server.

Thanks though!

**Comment by JoramD** [comment]
I'm assuming you are talking about [this](https://feedback.bistudio.com/T80668) issue? 

That is only an issue if the textures are in the mission pbo, which in this case does not apply since the textures are in a mod. I can confirm this after just now testing to make sure.

**Comment by jonpas** [comment]
Right, I forgot we have those in a mod.

**Comment by SyMP2005** [comment]
Awesome stuff! Thanks @JoramD0

**Pull request merged**
