### PR TITLE
Environment

### PR DESCRIPTION
**Pull request by Mike-MF**
- Disable Ambient Environment noises
- Hide Adv Marksman Markers.

### CODE REVIEW

**Comment by jonpas** [comment]
You hate bird chirping? :(

**Comment by Mike-MF** [comment]
I could barely hear Tim yesterday!

**Comment by jonpas** [comment]
There is a separate audio setting for it you know. :P

**Comment by Mike-MF** [comment]
But, no irritating environment sounds!

**Comment by jonpas** [comment]
Nature man, nature.

**Pull request merged**
