### PR TITLE
Change to cba_notify

### PR DESCRIPTION
**Pull request by JoramD**
**When merged this pull request will:**
- Change all `ace_common_fnc_displayTextStructured` calls to `cba_fnc_notify` for simplicity

### CODE REVIEW

**Review by jonpas — COMMENTED** [review]
I wouldn't remove the `[]` notation. Make sure things still show up ok as well and aren't cut-off.

**Comment by JoramD** [comment]
Will add the notation back in but the only I could do in case of text not fitting on one line is making the text smaller.

**Comment by jonpas** [comment]
Read the arguments of `CBA_fnc_notify` maybe?

**Comment by JoramD** [comment]
None of the text is cut off, it seems `cba_fnc_notify` adjusts by itself

**Review by jonpas — APPROVED** [review]

**Review by Mike-MF — APPROVED** [review]

**Pull request merged**
